name: Build SDK

on:
  workflow_dispatch:

jobs:
  build-typescript-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate SDK
        run: |
          npm install @openapitools/openapi-generator-cli -g
          make update
